---
title: "GEP: Evaluation of Groundwater Recharge (Regulation Services) Ecosystem Services: Literature Review"
author: Shunkei Kakimoto
format:
  html:
    page-layout: full
    theme: 
      - simple
    embed-resources: true
    number-sections: true
    number-depth: 3
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
    toc: true
    toc-depth: 3
    toc-expand: 3
    fontsize: 15pt
    bibliography: ../../2_Water_General.bib
    tbl-cap-location: top
engine: knitr
---

# Required Data Inputs
## Watershed
+ Area of Interest

## Topography

+ DEM (.tif)
+ Threshold flow accumulation

## Land Use/Land Cover

+ Curve numbers
+ Evapotranpiration coefficients

## Climate (monthly)
+ Monthly Precipitation (12 separated .tif files)
+ Monthly ET0 (12 separated .tif files)
+ Rain Events Table (csv)

## Soil (raster) (?)
+ Hydrologic soil groups (.tif)

## Parameters
+ Threshold flow accumulation: 10000
+ alpha_m Parameter: Default value is 1/12
  +  alpha should be set to the antecedent monthly precipitation values, relative to the total precipitation: Pm-1/Pannual
    + **Use Monthly Alpha Table (.csv)** 

    
+ beta_i Parameter: Default value is 1
+ gamma Parameter: Default value is 1



# List of Data

## WHYMAP: Groundwater Resources of the World: @Richts.etal2011
+ "WHYMAP_GWR"

+ Version 2 (WHYMAP Groundwater Resources of the World (v2)) is downloaded from https://ihp-wins.unesco.org/dataset/groundwater-resources-of-the-world


::: {.callout-note}
## Groundwater Resources of the World (WHYMAP GWR) (WMS)
The World-wide Hydrogeological Mapping and Assessment Programme (WHYMAP) provides data and information about the earth´s major groundwater resources. The Groundwater Resources Map shows various characteristic groundwater environments in their areal extent and classified by their aquifer productivity and recharge potential. Additional groundwater related features such as wetlands and areas of low rainfall are included in the dataset.
:::


## Global Geo-processed Data of Aquifer Properties by 0.5° Grid, Country and Water Basins

+ "9sany-rht26" (https://data.msdlive.org/records/9sany-rht26)


## Precipitation Data
+ WorldClim version 2.1 climate data for 1970-2000


## ET0




## Climate Zone:
+ Koppen-Geiger Climate Zone Classification Map (1991-2020) (https://data.naturalcapitalproject.stanford.edu/dataset/sts-b04939b0df93eb3f4305a065933c66122a0edc6fa425b157b99aa7b4b4446d20)




## World Data Grids from SWAT
+ "World_Data_Grids"
+ https://swat.tamu.edu/data/

This contains:

+ `country.shp`: Country boundaries


# NOTE:

+ SWY: ET0: https://community.naturalcapitalproject.org/t/seasonal-water-yield/4741


+ ET0 units for the Seasonal Water Yield module: https://community.naturalcapitalproject.org/t/et0-units-for-the-seasonal-water-yield-module/5501

+ Seasonal Water Yield Precipitation/Evapotranspiriation Rasters: https://community.naturalcapitalproject.org/t/seasonal-water-yield-precipitation-evapotranspiriation-rasters/565/1
+ says that precipitation and evapotranspiration rasters should be in mean monthly values.

+ @Scordo.etal2018 says:

> "The InVEST SWYM model requires monthly total precipitation and not daily totals; however, it also requires the number of precipitation events per month for the watershed that is being modeled as data input. To calculate the number of precipitation events per month, we averaged the total daily precipitation across all pixels contained within the boundaries of each GRDC watershed shape file. Days with an average precipitation per pixel of greater than 0.1 mm were counted as precipitation events and monthly totals were tabulated for inclusion in the SWYM run. Due to the requirement for monthly precipitation, we converted daily total precipitation to monthly total precipitation by summing the daily precipitation values at each pixel of the raster to create monthly precipitation rasters."




