# Task 3: Test Run

```{r}
# /*===========================================*/
#'=  Setup =
# /*===========================================*/
library(here)
library(data.table)
library(dplyr)
library(terra)
library(exactextractr)
library(sf)
library(tmap)
library(ggplot2)
library(tidyr)

# EPSG:8857
# WGS 84 / Equal Earth Greenwich

# espg_code <- 8857
espg_code <- 6933

# /*===== Path Setting =====*/
base_dt_dir <- "/Volumes/baseHD/NatCapTEEMs/GEP/GWR/Data"
tmp_save_dir <- here("Data/x_sample_data/1_task3")


# /*===== Load Functions =====*/
quarto::qmd_to_r_script(qmd = here("Scr/Code/InVEST_SWY/x_SWY_Functions.qmd"))
source(here("Scr/Code/InVEST_SWY/x_SWY_Functions.R"))
```


## AOI

```{r}
#| label: aoi
# === Original === # 
aoi_orig <- st_read(here("Data/x_sample_data/watershed_gura.shp"))

# aoi_orig_adj <- st_transform(aoi_orig, crs = st_crs(af_case_sf))

# === Test === #
# aoi_tg <- af_case_sf[aoi_orig_adj,]
# plot(aoi_tg$geometry)
# plot(aoi_orig_adj$geometry, add=TRUE, col="red")

st_write(
  st_transform(aoi_orig, crs = espg_code),
  # aoi_orig,
  here(tmp_save_dir, "aoi_guara_test.gpkg"),
  delete_dsn = TRUE,
  quiet = TRUE
)

aoi_test <- st_read(here(tmp_save_dir, "aoi_guara_test.gpkg"))
```

```{r}

fn_comp_prep_inputs(
  aoi_sf_var = aoi_test, 
  custom_aoi_provided = TRUE, 
  custom_region_abbr_var = "af", 
  custom_save_dir = tmp_save_dir
)

```