# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.15.1 on Sat Jul  5 13:57:14 2025
# Model: Seasonal Water Yield

import logging
import sys

import natcap.invest.seasonal_water_yield.seasonal_water_yield
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'alpha_m': '1/12',
    'aoi_path': '/Users/shunkeikakimoto/Dropbox/ResearchProject/GEP/GWR/Data/z_InVest_SampleData/Seasonal_Water_Yield/watershed_gura.shp',
    'beta_i': '1',
    'biophysical_table_path': '/Users/shunkeikakimoto/Dropbox/ResearchProject/GEP/GWR/Data/z_InVest_SampleData/Seasonal_Water_Yield/biophysical_table_gura_SWY.csv',
    'climate_zone_raster_path': '',
    'climate_zone_table_path': '',
    'dem_raster_path': '/Users/shunkeikakimoto/Dropbox/ResearchProject/GEP/GWR/Data/z_InVest_SampleData/Seasonal_Water_Yield/DEM_gura.tif',
    'et0_dir': '/Users/shunkeikakimoto/Dropbox/ResearchProject/GEP/GWR/Data/z_InVest_SampleData/Seasonal_Water_Yield/ET0_monthly',
    'flow_dir_algorithm': 'D8',
    'gamma': '1',
    'l_path': '',
    'lulc_raster_path': '/Users/shunkeikakimoto/Dropbox/ResearchProject/GEP/GWR/Data/z_InVest_SampleData/Seasonal_Water_Yield/land_use_gura.tif',
    'monthly_alpha': False,
    'monthly_alpha_path': '',
    'precip_dir': '/Users/shunkeikakimoto/Dropbox/ResearchProject/GEP/GWR/Data/z_InVest_SampleData/Seasonal_Water_Yield/Precipitation_monthly',
    'rain_events_table_path': '/Users/shunkeikakimoto/Dropbox/ResearchProject/GEP/GWR/Data/z_InVest_SampleData/Seasonal_Water_Yield/rain_events_gura.csv',
    'results_suffix': '',
    'soil_group_path': '/Users/shunkeikakimoto/Dropbox/ResearchProject/GEP/GWR/Data/z_InVest_SampleData/Seasonal_Water_Yield/soil_group_gura.tif',
    'threshold_flow_accumulation': '1000',
    'user_defined_climate_zones': False,
    'user_defined_local_recharge': False,
    'workspace_dir': '/Users/shunkeikakimoto/Dropbox/ResearchProject/GEP/GWR/Data/z_InVest_SampleData/x_output/SWY',
}

if __name__ == '__main__':
    natcap.invest.seasonal_water_yield.seasonal_water_yield.execute(args)
