---
title: "Preprocess NDVI Data for Analysis"
---


```{r}
library(here)
i_am("Scr/Code/x_PrepData/Prep_NDVI.qmd")


library(data.table)
library(terra)
library(sf)
library(dplyr)
library(ggplot2)
library(tmap)

# /*===== Path Configuration =====*/
source(here("Scr/Code/0_path_config.R"))
```

# Data Preparation

```{r}

# === List of NDVI files (2019)=== #
ls_navi_names <- list.files(
  file.path(raw_dir, "NDVI/MOD13C2_061-20250713_203352"), 
  full.names = FALSE
)

# === Load NDVI Data === #

ls_ndvi_raw <- 
  lapply(
    ls_navi_names, 
    function(x) {
      # x = ls_navi_names[1]

      file_path <- file.path(raw_dir, "NDVI/MOD13C2_061-20250713_203352", x)

      layer_raw <- rast(file_path, raw = TRUE) 

      layer <- layer_raw[['\"CMG 0.05 Deg Monthly NDVI\"']]
      
      layer <- layer * 0.0001

      # plot(layer)
      
      # Layer names
      day <- as.integer(sub(".*A\\d{4}(\\d{3})\\..*", "\\1", x))
      month <- month(as.Date(day, origin = paste0(substr(x, 10, 13), "-01-01")))
      names(layer) <- paste0("ndvi_m", month)
      
      return(layer)
    }
  ) %>%
  rast()


writeRaster(
  ls_ndvi_raw, 
  filename = file.path(raw_dir, "NDVI/ndvi_m_2019.tif"), 
  overwrite = TRUE
)
```